# -*- coding: utf-8 -*-
"""SB79_BayAreaStations_Ateam_.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ke3hGcYcq4309iVachGjduVlNhHKPkEL
"""

!pip install osmnx

import os
import pandas as pd
import numpy as np
import geopandas as gpd
import matplotlib.pyplot as plt
import seaborn as sns
from shapely.geometry import Point
import osmnx as ox
import networkx as nx
import folium

# configure OSMnx
ox.settings.log_console = True
print(ox.__version__)

PROJECT_CRS = "EPSG:26910"  # UTM Zone 10N (Bay Area)

"""**Load and Inspect Data**
*   Check basic structure: Use df.head(), df.tail(), and df.info() to inspect the first and last few rows, data types, and overall shape.
*   Check df.sample() to see a random sample.




"""

#Load and Inspect Data
file_path = 'https://raw.githubusercontent.com/deniarellano/A_team_midterm/refs/heads/main/data/raw/cdot_ca_transit_stops_-4086323185766993091.csv'
stations_df = pd.read_csv(file_path)
stations_df.head()
stations_df.tail()
print(stations_df.columns,'\n')
print(f"Dataset loaded with {stations_df.shape[0]} rows and {stations_df.shape[1]} columns.")

"""**Understand Data Types**
*   Check data types for each column
*   Identify which columns should be numeric, dates, or text
*   Flag columns stored incorrectly

"""

stations_df.info()

"""*General Transit Feed Specification(GTFS) route types*

* 0 - Tram, Streetcar, Light rail. Any light rail or street level system within a metropolitan area.

* 1 - Subway, Metro. Any underground rail system within a metropolitan area.
* 2 - Rail. Used for intercity or long-distance travel.
* 3 - Bus. Used for short- and long-distance bus routes.
* 4 - Ferry. Used for short- and long-distance boat service.
* 5 - Cable tram. Used for street-level rail cars where the cable runs beneath the vehicle (e.g., cable car in San Francisco).

"""

stations_df['Route Type'].value_counts()

#Making the route types column more legible for us to read and use
stations_df['Route Type'].value_counts()
stations_df['Route Type'] = stations_df['Route Type'].astype(str)
stations_df['Route Type'] = stations_df['Route Type'].str.split(',') #this would make it two distinct values for eg: '3', '5'
#At present ['Route Type'] consists of a list of values
#Explode the route types into separate rows so we can use replace based on a dictionary
stations_df = stations_df.explode('Route Type')
stations_df['Route Type'] = stations_df['Route Type'].str.strip()

#Create a dictionary
route_dict = {'0': 'Tram/Light Rail',
    '1': 'Subway/Metro',
    '2': 'Rail',
    '3': 'Bus',
    '4': 'Ferry',
    '5': 'Cable Tram'}

stations_df['route_type_defined'] = stations_df['Route Type'].replace(route_dict)
combined_rows = stations_df.groupby(level=0)['route_type_defined'].agg(','.join)

stations_df = stations_df[~stations_df.index.duplicated(keep='first')]
stations_df['route_type_defined'] = combined_rows

#We don't want separate rows - so group rows using original index(level=0) and then combine rows using .agg
stations_df['route_type_defined'].value_counts()
#stations_df.reset_index()

"""**Inspect Column Names (.columns)**
*   Check for unwanted characters such as #, %, @, etc.
*   Identify and remove whitespaces for easier column access.
*   Standardize case formatting (lowercase is generally easier to handle).
*   If necessary, rename columns systematically.
"""

#Remove whitespaces & lower case formatting
cleaned_stations_df = stations_df.copy()
cleaned_stations_df.columns = cleaned_stations_df.columns.str.replace(' ', '_').str.lower()

cleaned_stations_df.head()

#Drop columns that are not essential
stations_df_renamed = cleaned_stations_df.drop(columns=['objectid','agency_id','stop_id','route_type','meters_to_state_highway','agency_gtfs_feed'])
stations_df_renamed.head()

"""**Check index (df.index):**
*   Ensure uniqueness (df.index.is_unique).
*   Identify index data type (string, numeric, timestamp) to check for consistency.
*  Reset the index if necessary (df.reset_index(drop=True)).
*   Set an appropriate column as an index if required (df.set_index("column_name")).
"""

print(stations_df_renamed.index.is_unique)
stations_df_renamed.index.dtype

"""**Data Cleaning**

**Step 1: SB79 Applicable Bay Area Counties**
"""

#SB_79 Counties for Bay Area -  San Francisco, Alameda, San Mateo, and Santa Clara Counties which are included in target_districts
#Urban transit county means a county with more than 15 passenger rail stations
target_districts = ['04 - Bay Area / Oakland', '04 - Oakland']

cleaned_stations_df = stations_df_renamed[stations_df_renamed['caltrans_district'].isin(target_districts)]
cleaned_stations_df['caltrans_district'].unique()

"""**Data Cleaning**

**Step 2: SB79 Applicable Transit Agencies**
"""

SB79_applicable_transit_agencies = ['City and County of San Francisco' ,
                                    'Alameda-Contra Costa Transit District',
                                    'San Mateo County Transit District',
                                    'Santa Clara Valley Transportation Authority',
                                    'Peninsula Corridor Joint Powers Board',
                                    'San Francisco Bay Area Rapid Transit District']

cleaned_stations_df = cleaned_stations_df[cleaned_stations_df['agency_name'].isin(SB79_applicable_transit_agencies)]
cleaned_stations_df['agency_name'].unique()

"""**Step 3: Keeping only one instance of each stop name**"""

cleaned_stations_df = cleaned_stations_df.drop_duplicates(subset=['stop_name'])
cleaned_stations_df['stop_name'].is_unique

cleaned_stations_df.reset_index(drop=True)
cleaned_stations_df.index.is_unique

"""**Check Data quality**
*   Look for duplicates
*   Count missing values per column
*   Check for obvious errors or inconsistencies



"""

print(cleaned_stations_df.isna().sum()) #Prints sum of missing values across columns in dataframe

"""**Classify as Tier-1 and Tier-2 stations under SB79**

Criteria for classification:

**Tier 1**: Atleast 72 trains per day(heavy rail  or high frequency commuter rail in urban transit counties)

**Tier 2**: 48 - 72 trains per day(light rail transit, by high-frequency commuter rail, or by bus rapid transit)


"""

transit_not_included = ['Cable Tram','Bus/Cable Tram','Ferry']
cleaned_stations_df = cleaned_stations_df[~cleaned_stations_df['route_type_defined'].isin(transit_not_included)]
cleaned_stations_df['route_type_defined'].value_counts()

#There is a problem with this analysis - 'Tier 1' & 'Tier 2' stations are not being recorded because Northbound and Southbound stations are counted as two separate stations so many Tier 1 stations have lesser than 72 in Northbound and lesser than 72 in Southbound

#Create a new column for SB 79 tier classifications
cleaned_stations_df['SB79_tier'] = ''
#Transit types not included in tier 1
exclude= ['Bus', 'Tram/Light Rail', 'Tram/Light Rail,Bus']

#Create Tier 1 and Tier 2 masks based on condition
tier_1_mask = (cleaned_stations_df['number_of_arrivals']) >= 72 & ~(cleaned_stations_df['route_type_defined'].isin(exclude))

tier_2_mask = (cleaned_stations_df['number_of_arrivals'] >= 48) & (cleaned_stations_df['number_of_arrivals'] < 72)

na_mask = cleaned_stations_df['number_of_arrivals'] < 48 #Stations not applicable to SB79

cleaned_stations_df.loc[tier_1_mask, 'SB79_tier'] = 'Tier 1'
cleaned_stations_df.loc[tier_2_mask, 'SB79_tier'] = 'Tier 2'
cleaned_stations_df.loc[na_mask, 'SB79_tier'] = 'Not SB79 applicable'

cleaned_stations_df.head(10)
cleaned_stations_df['SB79_tier'].value_counts()

cleaned_stations_df['route_type_defined'].value_counts()

tier_1_transit = ['Rail','Subway/Metro']

tier_1_agency = (
    cleaned_stations_df[(cleaned_stations_df['route_type_defined'].isin(tier_1_transit))]
    .groupby('agency_name')
    .size()
    .reset_index(name='number_of_stations')
    .sort_values('number_of_stations', ascending=False)
)

print(tier_1_agency.head())

"""**Dropping Duplicate Stations**

The problem here is the same transit station has different number of arrival values depending on the number of routes and Route IDs. We want to keep only the station row with the highest arrival values.


"""

#Drop columns that are not essential
cleaned_stations_df = (cleaned_stations_df
    .sort_values('number_of_arrivals', ascending=False)
    .drop_duplicates(subset=['stop_name'], keep='first')
)

cleaned_stations_df['stop_name'].value_counts()
cleaned_stations_df.head()
cleaned_stations_df['stop_name'].is_unique

#Check
cleaned_stations_df['stop_name'].value_counts()
cleaned_stations_df.head()

#Check
check_station = cleaned_stations_df[cleaned_stations_df['stop_name'] == '12th Street / Oakland City Center']
check_station

"""**Creating a GeoData Frame**"""

stations_geom = gpd.points_from_xy(
    x=cleaned_stations_df['x'],
    y=cleaned_stations_df['y'])

stations_geom

stations_gdf= gpd.GeoDataFrame(
    cleaned_stations_df,
    geometry=stations_geom,
    crs=4326)

stations_gdf.head()

#Drop rows where SB79 is Not Applicable
stations_gdf.drop(stations_gdf[stations_gdf['SB79_tier'] == 'Not SB79 applicable'].index, inplace=True)

"""Locate Stations on a Map"""

#stations_geom = {
    #stop_name: Point(x, y)
    #for stop_name, x, y
    #in zip(cleaned_stations_df['stop_name'], cleaned_stations_df['x'], cleaned_stations_df['y'])}

stations_gdf = gpd.GeoDataFrame(
    cleaned_stations_df,
    geometry=gpd.points_from_xy(cleaned_stations_df['x'], cleaned_stations_df['y']),
    crs=4326
)

#if 'geometry' in stations_gdf.columns:
    #print("The 'geometry' column exists in the GeoDataFrame.")
    #print(stations_gdf.head())
#else:
    #print("The 'geometry' column does not exist in the GeoDataFrame.")

plt.figure(figsize=(10, 10))
stations_gdf.plot(marker='o', markersize=5, figsize=(10, 10))
plt.show()

stations_gdf.head()

#Tier 1 Map
stations_gdf.drop(stations_gdf[stations_gdf['route_type_defined'] == 'Bus'].index, inplace=True)

stations_area_tier_1 = stations_gdf[stations_gdf['SB79_tier'] == 'Tier 1'].to_crs(epsg=3857)
stations_area_tier_1['geometry'] = stations_area_tier_1.buffer(804)

m = stations_gdf.explore(
    color='red',
    name='Tier 1 Stations',
    scheme='quantiles',
    legend=True,
    tooltip=False,
    tiles='CartoDB positron',
    zoom_start=10)
stations_area_tier_1.explore(
    m=m,
    color='green',
    name='Tier 1 Stations',
    tooltip=False,
    alpha="0.2")
m

#Tier 1 Map Without buffers
stations_gdf.drop(stations_gdf[stations_gdf['route_type_defined'] == 'Bus'].index, inplace=True)

stations_area_tier_1 = stations_gdf[stations_gdf['SB79_tier'] == 'Tier 1'].to_crs(epsg=3857)

m = stations_gdf.explore(
    color='red',
    name='Tier 1 Stations',
    scheme='quantiles',
    legend=True,
    tooltip=False,
    tiles='CartoDB positron',
    zoom_start=10)
m
# from google.colab import files

# m.save('tier_1_map.html')
# files.download('tier_1_map.html')

from google.colab import drive
drive.mount('/content/drive')

cleaned_stations_df['route_type_defined'].value_counts()
tier_1_mask = (cleaned_stations_df['number_of_arrivals'] >= 72) & (cleaned_stations_df['route_type_defined'] != 'Bus')
tier_1_agency = (cleaned_stations_df[tier_1_mask]
    .groupby('agency_name')
    .size()
    .reset_index(name='number_of_stations')
    .sort_values('number_of_stations', ascending=False)
)
print(tier_1_agency.head())

tier_1_mask = (cleaned_stations_df['number_of_arrivals'] >= 72) & (cleaned_stations_df['route_type_defined'] !='Bus')
tier_2_mask = (cleaned_stations_df['number_of_arrivals'] >= 48) & (cleaned_stations_df['number_of_arrivals'] < 72)

tier_1_agency = (cleaned_stations_df[tier_1_mask]
    .groupby('agency_name')
    .size()
    .reset_index(name='number_of_stations')
    .sort_values('number_of_stations', ascending=False)
)

tier_2_agency = (cleaned_stations_df[tier_2_mask]
    .groupby('agency_name')
    .size()
    .reset_index(name='number_of_stations')
    .sort_values('number_of_stations', ascending=False)
)

print(tier_1_agency.head())
print(tier_2_agency.head())

# Symmetrical graph
import matplotlib.ticker as ticker
import numpy as np

all_agencies = sorted(set(tier_1_agency['agency_name']) | set(tier_2_agency['agency_name']))

agency_nickname = {
    "Alameda-Contra Costa Transit District": "AC Transit",
    "San Mateo County Transit District": "SamTrans",
    "Santa Clara Valley Transportation Authority": "VTA",
    "San Francisco Bay Area Rapid Transit District": "BART",
    "Peninsula Corridor Joint Powers Board": "Caltrain",
    "City and County of San Francisco": "Muni"
}

t1 = tier_1_agency.set_index('agency_name').reindex(all_agencies, fill_value=0)
t2 = tier_2_agency.set_index('agency_name').reindex(all_agencies, fill_value=0)

y = np.arange(len(all_agencies))

fig, ax = plt.subplots(figsize=(10, 8))

#Tier 1
ax.barh(y, t1['number_of_stations'].values, height=0.8, color='#f0a500', label='Tier 1')

#Tier 2
ax.barh(y, -t2['number_of_stations'].values, height=0.8, color='#a29bfe', label='Tier 2')

# Symmetric x-axis
max_count = max(t1['number_of_stations'].max(), t2['number_of_stations'].max()) + 2
ax.set_xlim(-max_count, max_count)

# Show absolute values on x-axis
ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: int(abs(x))))

# Agencies
agency_labels = [agency_nickname.get(agency, agency) for agency in all_agencies]

ax.set_yticks(y)
ax.set_yticklabels(agency_labels, fontsize=9)

# Direct labels instead of legend
ax.text(-max_count * 0.5, len(all_agencies), 'Tier 2', ha='center',
        fontsize=11, fontweight='bold', color='#a29bfe')
ax.text(max_count * 0.5, len(all_agencies), 'Tier 1', ha='center',
        fontsize=11, fontweight='bold', color='#f0a500')

# Center spine
ax.spines[['top', 'right', 'left']].set_visible(False)
ax.axvline(0, color='white', linewidth=1.5)

ax.set_xlabel('Number of Stations')
ax.set_title('SB79 Stations by Agency and Tier')
plt.tight_layout()
plt.show()

import geopandas as gpd
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

# Group by agency and route type
route_counts = (stations_gdf
    .groupby(['agency_name', 'route_type_defined'])
    .size()
    .reset_index(name='count')
)

# Pivot so each route type becomes a column
route_pivot = route_counts.pivot(index='agency_name', columns='route_type_defined', values='count').fillna(0)

# Apply nicknames if available
route_pivot.index = [agency_nickname.get(name, name) for name in route_pivot.index]

# Plot grouped bar chart
fig, ax = plt.subplots(figsize=(12, 6))
route_pivot.plot(kind='bar', ax=ax, colormap='Set2', width=0.8)

plt.xticks(rotation=45, ha='right')
ax.set_ylabel('Number of Stations')
ax.set_xlabel('')
ax.set_title('Route Types per Agency')
ax.legend(title='Route Type', bbox_to_anchor=(1.05, 1), loc='upper left')
ax.spines[['top', 'right']].set_visible(False)
plt.tight_layout()
plt.show()